cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 100
  size: 500
encoding_name: cl100k_base
extract_graph:
  entity_types:
  - organization
  - person
  - geo
  - event
  - specific object
  - abstract object
  max_gleanings: 1
  model_id: default_chat_model
  prompt: prompts/extract_graph.txt
input:
  base_dir: C:\Users\ericz\Documents\GitHub\Second-Me\resources/L1/processed_data/subjective
  file_encoding: utf-8
  file_pattern: .*\.txt$$
  file_type: text
  type: file
models:
  default_chat_model:
    api_base: https://generativelanguage.googleapis.com
    api_key: AIzaSyBny8Xv88srUtlcsIsQ0MgFsbIPen5YN0w
    async_mode: threaded
    auth_type: api_key
    concurrent_requests: 2
    encoding_model: cl100k_base
    max_retries: -1
    model: gemini-3-pro-preview
    model_supports_json: true
    requests_per_minute: 0
    retry_strategy: native
    tokens_per_minute: 0
    type: openai_chat
  default_embedding_model:
    api_base: https://generativelanguage.googleapis.com
    api_key: AIzaSyBny8Xv88srUtlcsIsQ0MgFsbIPen5YN0w
    async_mode: threaded
    auth_type: api_key
    concurrent_requests: 2
    encoding_model: cl100k_base
    max_retries: -1
    model: text-embedding-004
    model_supports_json: true
    requests_per_minute: 0
    retry_strategy: native
    tokens_per_minute: 0
    type: openai_embedding
output:
  base_dir: C:\Users\ericz\Documents\GitHub\Second-Me\resources/L1/graphrag_indexing_output/subjective
  type: file
reporting:
  base_dir: C:\Users\ericz\Documents\GitHub\Second-Me\resources/L1/graphrag_indexing_output/subjective\../report
  type: file
snapshots:
  embeddings: false
  graphml: false
summarize_descriptions:
  max_length: 500
  model_id: default_chat_model
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false
workflows:
- create_base_text_units
- create_final_documents
- extract_graph
- finalize_graph
